Filter
wolox-training/aa-graphql pull request #4
Opened 2019-08-06 17:11 UTC by aleacevedo

## Summary

Add filter option to get all albums query

## Trello Card

https://trello.com/c/cqUr60Hm/14-listado-de-albums-filtrado

2019-08-06 17:23 UTC, gonziesc requested changes

2019-08-06 17:23 UTC, gonziesc commented on app/services/album.js
> +        return albums.filter(album => album.title === filter);
dont modify param!

2019-08-07 14:56 UTC, gonziesc submitted a review, later dismissed

2019-08-07 14:56 UTC, gonziesc commented on app/services/album.js
> +        return sortedAlbums.filter(album => album.title === filter);
if you return here, you are not ordering!

2019-08-08 14:18 UTC, igna92ts requested changes

2019-08-08 14:18 UTC, igna92ts commented on app/services/album.js
> +        processedAlbums.sort((a, b) => {
this function seems a little bloated, how about making a separate function for sorting this?

2019-08-08 17:39 UTC, igna92ts approved these changes

2019-08-08 17:44 UTC, igna92ts approved these changes

2019-08-09 14:04 UTC, merged